locale = {
  'lang': 'es',
  'title': 'Aprendé hoy un nuevo idioma',
  'by': 'por',
  'learn_title': 'Basta de pasar horas memorizando <strong>el verbo to be</strong>',
  'learn': 'Aprendé hoy un nuevo idioma y aumentá tus posibilidades laborales, mejorá tu CV, preparate para un viaje o un intercambio y comunicá tus ideas a todo el mundo! Las clases online son ideales para personas como vos, que son ocupadas, ambiciosas, que necesitan aprender el inglés o el portugués, pero no se adaptaron a los métodos tradicionales de los cursos de idiomas. Nuestras clases son preparadas de acuerdo con las necesidades de cada alumno, después de una entrevista inicial, y pueden ser enfocadas en conversación, tópicos específicos de gramática o pronunciación, vocabulario técnico, preparación para exámenes de proficiencia, entrevistas de empleo, viajes de turismo o negocios. Usamos varios materiales, desde los libros tradicionales hasta flashcards de vocabulario, canciones, videos, noticias y todo lo que pueda ayudarte a aprender un idioma de forma entretenida, dinámica y práctica. No vas a pasar horas y horas memorizando el verbo to be! Para más información <a href="info.html">hacé click acá</a>.',
   'me_title': 'Quién soy yo?',
   'me': 'Soy Sam y desde los 15 años doy clases de inglés y portugués. Trabajé en institutos de idiomas en Brasil, como Leonze e Youmove, y también en Argentina, con el instituto Bridge. Dí clases particulares online y a domicilio, atendí tanto niños como adolescentes y adultos, y desarrollé cursos especializados en inglés/portugués para negocios, turismo, preparación para entrevistas y exámenes de proficiencia. Estudié en la UFPR, una de las más importantes universidades públicas de Brasil. Y ahora tenés la oportunidad de aprender conmigo, de forma dinámica y personalizada, el idioma que siempre quisiste aprender, pero quizás nadie te lo pudo enseñar todavía.',
   'how_title': 'Cómo funciona?',
   'how': 'Las clases online son preparadas de acuerdo con las necesidades de cada alumno, después de una entrevista inicial, y tienen la duración de una o dos horas. Se recomienda un mínimo de 2 horas semanales para obtener buenos resultados en un plazo mediano, y al menos 5 horas de clases semanales para un ritmo más intensivo. Para las clases, es necesario tener una conexión estable, cámara y micrófono. Se usan distintos materiales a depender de la necesidad del alumno, incluso libros de gramática, flashcards de vocabulario, canciones, videos, noticias, etc.',
   'who_title': 'Quiénes pueden tener clases?', 
   'who': 'Cualquier persona de cualquier parte del mundo puede tener clases conmigo, desde que sean comprometidos y se dediquen a estudiar. Acepto todos los niveles, desde personas que nunca tuvieron contacto con el idioma hasta personas que tienen un buen nivel oral y escrito y deseen practicar conversación o enfocarse en tópicos específicos de gramática o pronunciación. Como las clases son personalizadas, podemos crear juntos un cronograma que se ajuste a tus horarios y necesidades. Las personas que viven en la Ciudad Autónoma de Buenos Aires tienen la opción de tener clases presenciales a domicilio.',
   'howmuch_title': 'Cuánto sale? Cómo puedo pagar?', 
   'howmuch': 'Como las clases son altamente personalizadas, puede ser que el valor de la hora cambie a depender de las necesidades de cada alumno. En general, el precio varía de 11 a 17 dólares americanos por hora, pagos por transferencia o depósito bancario (Argentina), transferencia o depósito bancario (Brasil) o Paypal (todos los países).',
   'contact': ''

}
