locale = {
  'lang': 'en',
  'title': 'Learn a new language today',
  'by': 'by',
  'learn_title': 'The  <strong>"repeat after me"</strong> is over!',
  'learn': 'Learn a new language and improve your work possibilities, boost your resumee, prepare yourself for the trip of your life and comunicate with the world! These online classes are perfect for people like you, busy, ambitious, needing to learn Spanish or Portuguese but tired of trying the traditional language courses. Our classes are prepared according to the needs of each student, after an interview, and can be focused on conversation, specific grammar or pronunciation issues, technical vocabulary, preparation for proficiency exams or job interviews, tourism or business. We use a variety of materials, from traditional textbooks to vocabulary flashcards, songs, videos, news and everything that might help you learning a new language in a fun, dynamic and practical way. The "repeat after me" is finally over! For more info <a href="info.html">click here</a>.',
   'me_title': 'Who am I?',
   'me': 'I\'m Sam and I\'ve been teaching Portuguese and Spanish since I was 15. I\'ve worked in Brazilian language schools such as Leonze and Youmove, and schools in Argentina, such as Bridge. I teach private classes, online classes, classes for children, teenagers and adults, and I have created specialized courses for those who want to learn Business Portuguese, Business Spanish, courses focused on tourism, proficiency exams, job interviews, among others. I\'ve studied at UFPR, one of the most important public universities in Brazil, and now you have the opportunity to learn the greatest Latin American languages in a fun, dynamic and customized way!',
   'how_title': 'How does it work?',
   'how': 'The online classes are prepared according to the needs of each students, after an interview. Each class usually lasts one or two hours, and it\'s recommended to take at least two hours per week to obtain good results in a few months. If you want a more intensive course, you should ideally take 5 hours per week. It\'s important to have a stable internet connection, camera and microphone to take the classes. We use a variety of materials, from traditional textbooks to vocabulary flashcards, songs, videos, news and many other. The "repeat after me" is finally over!',
   'who_title': 'Who can take these classes?',
   'who': 'Anyone from all parts of the world can learn Spanish and Portuguese with me! The only requirement is that you are a dedicated student, willing to take the classes seriously. You can start today even if you\'ve never been in contact with those languages before, and you can improve your skills even if you already have a good level, and wish to focus on conversation, specific grammar or pronunciation issues, technical vocabulary, preparation for proficiency exams or job interviews, tourism or business. The classes are customized, so we can create a cronogram that fits your schedule and needs.',
   'howmuch_title': 'How much does it cost? How can I pay?',
   'howmuch': 'The classes are highly customized, that means that the hourly rate can vary from student to student. Generally, the hourly rate ranges from USD 11 to USD 17, and you can pay via Paypal. For other payment methods, please  <a href="contact.html">contact me here</a>.',
   'contact': ''
}
